[package]
name = "rote"
version = "0.2.96"
authors = ["Ryan1729 <Ryan1729@gmail.com>"]
license = "MIT and Apache 2.0"
edition = "2018"

[workspace]

members = [
    "libs/editor",
    "libs/macros",
    "libs/perf_viz",
    "libs/platform_types",
]